### ISSUE TITLE
"Ser simples de configurar" (Docker)

### ISSUE THREAD

**Issue by wellington1993** [wellington1993/avaliacao_desenvolvedor#2]
- [ ] Docker
- [ ] Scripts
- [ ] Documentação
- [ ] Teste em mais de um ambiente

**Comment by wellington1993** [comment]
Usando...

### Ruby:
```c
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
```

### Rails:
```c
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ rails -v
Rails 6.1.3.1
```

### Bundler:
```c
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ bundler -v
Bundler version 2.2.16
```

### Linux:
```ini
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ cat /etc/*release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic
```

### Docker:
```yaml
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

### Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### OpenSSL:
```c
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```

### Kernel:
```c
note@note-1-01UL:~/projetos/avaliacao_desenvolvedor$ uname -a 
Linux note-1-01UL 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
